# Numpy:
NumPy, short for Numerical Python, is a fundamental package for numerical computing in Python. It provides support for multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on these arrays efficiently. 

## Installation of Numpy
!pip install numpy

## Importing Numpy module

In [1]:
import numpy as np

##  Version of Numpy

In [2]:
np.__version__

'1.21.5'

In [3]:
np.version.version

'1.21.5'

# Functions in Numpy module

## a.Creating Arrays

In NumPy, there are several functions for creating arrays with specific patterns or values. Here are some commonly used ones

## 1.np.array():
Creates an array from a Python list or tuple.

## Syntax:
np.array(object,dtype=None,copy=True,ndmin=0)

In [4]:
list1=[1,2,3,4,5]
arr=np.array(list1,dtype=int,ndmin=2)
arr

array([[1, 2, 3, 4, 5]])

## 2.np.zeros():
Creates an array of all zeros.

## Syntax:
np.zeros(shape,dtype=None)

In [5]:
arr2=np.zeros((3,4),dtype=float)
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3.np.ones():
Creates an array of all ones.

## Syntax:
np.ones(shape,dtype=None)

In [6]:
arr2=np.ones((3,4),dtype=float)
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## 4.np.full():
Creates an array with specific element/value.

## Syntax:
np.full(shape,fill_value,dtype=None)

In [7]:
arr2=np.full((3,4),8,dtype=float)
arr2

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

## 5.numpy.arange(): 
Creates an array with a specified range.

## Syntax:
np.arange(start,stop,step,dtype)

In [8]:
arr2=np.arange(1,21,3)
arr2

array([ 1,  4,  7, 10, 13, 16, 19])

## 6.numpy.linspace(): 
Creates an array with evenly spaced values.

## Syntax:
np.linspace(start,stop,num,endpoint=True,dtype=None)

In [9]:
arr2=np.linspace(1,100,5,endpoint=True,dtype=int)
arr2

array([  1,  25,  50,  75, 100])

In [10]:
arr2=np.linspace(1,100,5,endpoint=False,dtype=int)
arr2

array([ 1, 20, 40, 60, 80])

## 7.np.identity():
Creates a square identity matrix. An identity matrix is a square matrix in which all the elements of the principal diagonal are ones, and all other elements are zeros.

## Syntax:
np.identity(n,dtype=None)

In [11]:
arr2=np.identity(3,dtype=int)
arr2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## 8.np.eye():
Creates a identity matrix of order M N,but it creates a rectangular matrix if N and M are not equal.

## Syntax:
np.eye(N,M=0,dtype=<class float>)

In [12]:
arr2=np.eye(3)
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr2=np.eye(3,4)
arr2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 9.np.diag():
np.diag() is a versatile function in NumPy that can be used to construct diagonal matrices, extract diagonal elements from matrices, or construct or extract specific diagonals from arrays. Its behavior depends on the input provided
    
## Syntax:
np.diag(v)

In [14]:
arr3=np.diag(arr2)
arr3

array([1., 1., 1.])

In [15]:
arr4=np.diag([1,2,3,4])
arr4

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

# Array Attributes

In NumPy, arrays have several attributes that provide information about their size, shape, data type, and more. Some commonly used array attributes include

## 1.ndarray.shape:
Returns the shape of the array.

In [16]:
arr=np.array([[1,2,3,4],[5,56,7,8]],dtype=float)
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5., 56.,  7.,  8.]])

In [17]:
arr.shape

(2, 4)

## 2.ndarray.ndim:
Returns the number of dimensions (axes) of the array.

In [18]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5., 56.,  7.,  8.]])

In [19]:
arr.ndim

2

## 3.ndarray.size:
Returns the total number of elements in the array.

In [20]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5., 56.,  7.,  8.]])

In [21]:
arr.size

8

## 4.ndarray.dtype:
Returns the data type of the elements in the array.

In [22]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5., 56.,  7.,  8.]])

In [23]:
arr.dtype

dtype('float64')

# Array Manipulation


Array manipulation in NumPy involves various operations for reshaping, slicing, joining, and splitting arrays. Here are some commonly used array manipulation functions in NumPy:

## 1.ndarray.reshape():
Reshape an array into a new shape.

## Syntax:
ndarray.reshape(shape)

In [24]:
arr

array([[ 1.,  2.,  3.,  4.],
       [ 5., 56.,  7.,  8.]])

In [25]:
arr.reshape(4,2)

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5., 56.],
       [ 7.,  8.]])

## 2.ndarray.copy():
A copy creates an array with its own data,completely independent of the original array.

## Syntax:
ndarray.copy()

In [26]:
arr=np.array([1,2,3,4])
arr1=arr.copy()
arr1[0]=10
print("After modifications")
print(arr1)
print("Original Array ")
print(arr)

After modifications
[10  2  3  4]
Original Array 
[1 2 3 4]


## 3.ndarray.view():
A view creates a new array object that reference the same data as the original array.

## Syntax:
ndarray.view()

In [27]:
arr=np.array([1,2,3,4])
arr1=arr.view()
arr1[0]=10
print("After modifications")
print(arr1)
print("Original Array ")
print(arr)

After modifications
[10  2  3  4]
Original Array 
[10  2  3  4]


## 4.ndarray.flatten():
flatten the array,changes made in the flattened array doesn't affect the original array.

## Syntax:
ndarray.flatten()

In [28]:
arr

array([10,  2,  3,  4])

In [29]:
arr1=arr.flatten()
arr1

array([10,  2,  3,  4])

In [30]:
#changing the value of arr1 at 2nd index to 200.78
arr1[2]=200.78
arr1

array([ 10,   2, 200,   4])

In [31]:
#Original array
arr

array([10,  2,  3,  4])

## 5.ndarray.ravel():
flatten the array,changes made in the ravel array affects the original array.

## Syntax:
ndarray.ravel()

In [32]:
arr

array([10,  2,  3,  4])

In [33]:
arr1=arr.ravel()
arr1

array([10,  2,  3,  4])

In [34]:
#changing the value of arr1 at 2nd index to 200.78
arr1[2]=200.78
arr1

array([ 10,   2, 200,   4])

In [35]:
#Original Array
arr

array([ 10,   2, 200,   4])

## 6.np.concatenate():
numpy.concatenate(): Concatenate arrays along a specified axis.
    
## Syntax:
np.concatenate([a1,a2],axis=0,dtype=None)

In [36]:
arr1=np.arange(1,21).reshape(5,4)
arr2=np.arange(11,31).reshape(5,4)
arr3=np.concatenate([arr1,arr2],axis=1)
arr3

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18],
       [ 9, 10, 11, 12, 19, 20, 21, 22],
       [13, 14, 15, 16, 23, 24, 25, 26],
       [17, 18, 19, 20, 27, 28, 29, 30]])

In [37]:
arr3=np.concatenate([arr1,arr2],axis=0)
arr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

## 7.np.vstack():
Vertically stacks arrays one on the top of the other,the arrays must have same number of colunns.

## Syntax:
np.vstack([a1.a2])

In [38]:
arr1,arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22],
        [23, 24, 25, 26],
        [27, 28, 29, 30]]))

In [39]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

## 8.np.hstack():
Horizontally stacks arrays side by side,the arrays must have same number of rows.

## Syntax:
np.hstack([a1,a2])

In [40]:
arr1,arr2

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]),
 array([[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22],
        [23, 24, 25, 26],
        [27, 28, 29, 30]]))

In [41]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18],
       [ 9, 10, 11, 12, 19, 20, 21, 22],
       [13, 14, 15, 16, 23, 24, 25, 26],
       [17, 18, 19, 20, 27, 28, 29, 30]])

# Basic Mathematical Functions

NumPy provides a wide range of mathematical functions that operate element-wise on arrays. Here are some commonly used mathematical functions in NumPy:


## 1.np.add(): 
Add corresponding elements of two arrays.

## Syntax:
np.add(*args.**kwargs)

In [42]:
a1=np.array([1,2,3,4,5])
a2=np.array([4,5,6,7,8])
np.add(a1,a2)

array([ 5,  7,  9, 11, 13])

## 2.np.subtract():
Subtracts corresponding elements of two arrays.

## Syntax:
np.subtract(*args.**kwargs)

In [43]:
a1=np.array([1,2,3,4,5])
a2=np.array([4,5,6,7,8])
np.subtract(a1,a2)

array([-3, -3, -3, -3, -3])

## 3.np.multiply():
Multiplies corresponding elements of two arrays.

## Syntax:
np.multiply(*args.**kwargs)

In [44]:
a1=np.array([1,2,3,4,5])
a2=np.array([4,5,6,7,8])
np.multiply(a1,a2)

array([ 4, 10, 18, 28, 40])

## 4.np.divide():
Divides corresponding elements of two arrays.

## Syntax:
np.divide(*args.**kwargs)

In [45]:
a1=np.array([1,2,3,4,5])
a2=np.array([4,5,6,7,8])
np.divide(a1,a2)

array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ])

## 5.np.mod():
Gives the remainder of corresponding elements of two arrays.

## Syntax:
np.mod(*args.**kwargs)

In [46]:
a1=np.array([1,2,3,4,5])
a2=np.array([4,5,6,7,8])
np.mod(a1,a2)

array([1, 2, 3, 4, 5], dtype=int32)

## 6.np.min():
Returns minimum value of the given array along specified axis.

## Syntax:
np.min(a,axis=Npne)

In [47]:
a1=np.arange(1,51).reshape(5,10)
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [48]:
np.min(a1,axis=0)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
np.min(a1,axis=1)

array([ 1, 11, 21, 31, 41])

In [50]:
np.min(a1)

1

## 7.np.max():
Returns maximum value of the given array along specified axis.

## Syntax:
np.max(a,axis=Npne)

In [51]:
a1=np.arange(1,51).reshape(5,10)
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [52]:
np.max(a1,axis=0)

array([41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [53]:
np.max(a1,axis=1)

array([10, 20, 30, 40, 50])

In [54]:
np.max(a1)

50

## 9.np.argmax():
Returns the indices of the maximum values along an axis.

## Syntax:
np.argmax(a,axis=None)

In [55]:
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [56]:
np.argmax(a1)

49

In [57]:
np.argmax(a1,axis=0)

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4], dtype=int64)

In [58]:
np.argmax(a1,axis=1)

array([9, 9, 9, 9, 9], dtype=int64)

## 10.np.argmin():
Returns the indices of the minimum values along an axis.

## Syntax:
np.argmin(a,axis=None)

In [59]:
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [60]:
np.argmin(a1)

0

In [61]:
np.argmin(a1,axis=0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [62]:
np.argmin(a1,axis=1)

array([0, 0, 0, 0, 0], dtype=int64)

## 11.np.floor():
Returns the floor of each element in an array.

## Syntax:
np.floor(a1)

In [63]:
a2=np.array([1.98,2.1,2.91,2.000001,8.6])
a2

array([1.98    , 2.1     , 2.91    , 2.000001, 8.6     ])

In [64]:
np.floor(a2)

array([1., 2., 2., 2., 8.])

## 12.np.ceil():
Returns the ceil of every element in an array.

## Syntax:
np.ceil(a1)

In [65]:
a2

array([1.98    , 2.1     , 2.91    , 2.000001, 8.6     ])

In [66]:
np.ceil(a2)

array([2., 3., 3., 3., 9.])

## 13.np.sum():
np.sum() is a NumPy function used to compute the sum of array elements along a specified axis or axes. It can operate on arrays of any dimension

## Syntax:
np.sum(a,axis=None)

In [67]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [68]:
np.sum(arr1)

210

In [69]:
np.sum(arr1,axis=1)

array([10, 26, 42, 58, 74])

In [70]:
np.sum(arr1,axis=0)

array([45, 50, 55, 60])

## 14.np.prod():
np.prod() is a NumPy function used to compute the product of array elements along a specified axis or axes. It can operate on arrays of any dimension

## Syntax:
np.prod(a,axis=None)

In [71]:
np.prod(np.array([1,2,3,4]))

24

# Trigonometric Functions


In NumPy, trigonometric functions are available to perform various trigonometric operations on arrays. Here are the main trigonometric functions provided by NumPy:

## 1.np.sin():
Computes the sine value of each element in an array.

## Syntax:
np.sin(**args,***kwargs)

In [72]:
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [73]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
        -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111],
       [-0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
        -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525],
       [ 0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
         0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162],
       [-0.40403765,  0.55142668,  0.99991186,  0.52908269, -0.42818267,
        -0.99177885, -0.64353813,  0.29636858,  0.96379539,  0.74511316],
       [-0.15862267, -0.91652155, -0.83177474,  0.01770193,  0.85090352,
         0.90178835,  0.12357312, -0.76825466, -0.95375265, -0.26237485]])

## 2.np.cos():
Computes the cos value of each element in an array.

## Syntax:
np.cos(**args,***kwargs)

In [74]:
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [75]:
np.cos(a1)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
        -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206],
       [-0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
         0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145],
       [ 0.91474236,  0.83422336, -0.01327675, -0.84857027, -0.90369221,
        -0.12796369,  0.76541405,  0.95507364,  0.26664293, -0.66693806],
       [-0.98733928, -0.39998531,  0.5551133 ,  0.99984331,  0.52532199,
        -0.43217794, -0.99233547, -0.64014434,  0.30059254,  0.96496603]])

## 3.np.tan():
Computes the tan value of each element in an array.

## Syntax:
np.tan(**args,***kwargs)

In [76]:
a1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [77]:
np.tan(a1)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01, -6.79971146e+00, -4.52315659e-01,
         6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
         3.49391565e+00, -1.13731371e+00,  1.51589471e-01,
         2.23716094e+00],
       [-1.52749853e+00,  8.85165604e-03,  1.58815308e+00,
        -2.13489670e+00, -1.33526407e-01,  1.17875355e+00,
        -3.27370380e+00, -2.81429605e-01,  8.87142844e-01,
        -6.40533120e+00],
       [-4.41695568e-01,  6.61006041e-01, -7.53130148e+01,
        -6.23498963e-01,  4.73814720e-01,  7.75047091e+00,
        -8.40771255e-01,  3.10309661e-01,  3.61455441e+00,
        -1.11721493e+00],
       [ 1.60656699e-01,  2.29138799e+00, -1.49838734e+00,
         1.77046993e-02,  1.61977519e+00, -2.08661353e+00,
        -1.24527568e-01,  1.20012724e+00, -3.17290855e+00,
        -2.

# Inverse-Trigonometric Functions


In NumPy, inverse trigonometric functions are provided to compute the angles whose trigonometric functions yield specific values. Here are the main inverse trigonometric functions available in NumPy

## 1.arcsin():
Computes the inverse-sin of the given array.

## Syntax:
np.arcsin(**args,***kwargs)

In [78]:
a1=np.array([0,1,0,1])
a1

array([0, 1, 0, 1])

In [79]:
np.arcsin(a1)

array([0.        , 1.57079633, 0.        , 1.57079633])

## 2.arccos():
Computes the inverse-cos of the given array.

## Syntax:
np.arccos(**args,***kwargs)

In [80]:
a1

array([0, 1, 0, 1])

In [81]:
np.arccos(a1)

array([1.57079633, 0.        , 1.57079633, 0.        ])

## 3.arctan():
Computes the inverse-tan of the given array.

## Syntax:
np.arctan(**args,***kwargs)

In [82]:
a1

array([0, 1, 0, 1])

In [83]:
np.arctan(a1)

array([0.        , 0.78539816, 0.        , 0.78539816])

# Hyperbolic Functions


In NumPy, hyperbolic functions are provided to compute hyperbolic trigonometric operations on arrays. Here are the main hyperbolic functions available in NumPy

## 1.np.sinh():
Computes the Hyperbolic sine of an array.

## Syntax:
np.sinh(**args,***kwargs)

In [84]:
a1

array([0, 1, 0, 1])

In [85]:
np.sinh(a1)

array([0.        , 1.17520119, 0.        , 1.17520119])

## 2.np.cosh():
Computes the Hyperbolic cos of an array.

## Syntax:
np.cosh(**args,***kwargs)

In [86]:
a1

array([0, 1, 0, 1])

In [87]:
np.cosh(a1)

array([1.        , 1.54308063, 1.        , 1.54308063])

## 3.np.tanh():
Computes the Hyperbolic tan of an array.

## Syntax:
np.tanh(**args,***kwargs)

In [88]:
a1

array([0, 1, 0, 1])

In [89]:
np.tanh(a1)

array([0.        , 0.76159416, 0.        , 0.76159416])

# Invesre-Hyperbolic Functions


In NumPy, inverse hyperbolic functions are provided to compute the inverse hyperbolic trigonometric operations on arrays. Here are the main inverse hyperbolic functions available in NumPy:

## 1.arcsinh():
Computes Inverse Hyperbolic sine of an array.

## Syntax:
np.arcsinh(**args,***kwargs)

In [90]:
a1

array([0, 1, 0, 1])

In [91]:
np.arcsinh(a1)

array([0.        , 0.88137359, 0.        , 0.88137359])

## 2.np.arccosh():
Computes Invsers Hyperbolic cos of an array.

## Syntax:
np.arccosh(**args,***kwargs)

In [92]:
a1

array([0, 1, 0, 1])

In [93]:
np.arccosh(a1)

C:\Users\RAGHAVENDRA KUMAR\AppData\Local\Temp\ipykernel_29152\1637439351.py:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(a1)


array([nan,  0., nan,  0.])

## 3.np.arctanh():
Computes Invsers Hyperbolic tan of an array.

## Syntax:
np.arctanh(**args,***kwargs)

In [94]:
a1

array([0, 1, 0, 1])

In [95]:
np.arctanh(a1)

C:\Users\RAGHAVENDRA KUMAR\AppData\Local\Temp\ipykernel_29152\1974361636.py:1: RuntimeWarning: divide by zero encountered in arctanh
  np.arctanh(a1)


array([ 0., inf,  0., inf])

# Conversion Functions:



## 1.np.deg2rad(x): 
Convert angles from degrees to radians.

## Syntax:
np.deg2rad(**args,***kwargs)


In [96]:
x1=np.array([0,45,90,180])
np.deg2rad(x1)

array([0.        , 0.78539816, 1.57079633, 3.14159265])

## 2.np.rad2deg(x): 
Convert angles from radians to degrees.

## Syntax:
np.deg2rad(**args,***kwargs)


In [97]:
x1=np.array([0,45,90,180])
np.rad2deg(x1)

array([    0.        ,  2578.31007809,  5156.62015618, 10313.24031235])

# Statistical Functions

NumPy provides a variety of statistical functions for analyzing data stored in arrays. These functions can calculate various statistical measures such as mean, median, standard deviation, variance, and more. Here are some commonly used statistical functions in NumPy:



## 1.np.mean():
Computes mean along the specified axis on the given array.

## Syntax:
np.mean(a,axis=None)

In [98]:
x1=np.arange(1,10).reshape(3,3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
np.mean(x1)

5.0

In [100]:
np.mean(x1,axis=0)

array([4., 5., 6.])

In [101]:
np.mean(x1,axis=1)

array([2., 5., 8.])

## 2.np.median():
Computes median along the specified axis on the given array.

## Syntax:
np.median(a,axis=None)

In [102]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
np.median(x1)

5.0

In [104]:
np.median(x1,axis=0)

array([4., 5., 6.])

In [105]:
np.median(x1,axis=1)

array([2., 5., 8.])

## 3.np.var():
Computes variance along the specified axis on the given array.

## Syntax:
np.var(a,axis=None)

In [106]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
np.var(x1)

6.666666666666667

In [108]:
np.var(x1,axis=0)

array([6., 6., 6.])

In [109]:
np.var(x1,axis=1)

array([0.66666667, 0.66666667, 0.66666667])

## 4.np.std():
Computes standard deviation along the specified axis on the given array.

## Syntax:
np.std(a,axis=None)

In [110]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.std(x1)

2.581988897471611

In [112]:
np.std(x1,axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [113]:
np.std(x1,axis=0)

array([2.44948974, 2.44948974, 2.44948974])

# Random functions


NumPy provides a powerful suite of functions for generating random numbers and random arrays with various distributions. These functions are part of the numpy.random module. Here are some commonly used random functions in NumPy:

## 1.np.random.rand():
Returns a random float between 0 and 1.

## Syntax:
np.random.rand(shape)


In [114]:
np.random.rand(3,4)

array([[0.59442781, 0.76966253, 0.32153668, 0.17426291],
       [0.22982538, 0.90721924, 0.08255052, 0.4795993 ],
       [0.63240161, 0.10213286, 0.30128344, 0.07397356]])

In [115]:
np.random.rand(4)

array([0.99479348, 0.49213411, 0.67309538, 0.90851997])

In [116]:
np.random.rand()

0.23474490629557365

## 2.np.random.randint():
The np.random.randint() function generates random integers within a specified range. It's similar to the random.randint()

## Syntax:
np.random.randint(start,stop,size=None)-----End is inclusive

In [117]:
np.random.randint(1,10,(5,2))

array([[9, 8],
       [9, 6],
       [9, 7],
       [1, 3],
       [9, 9]])

## 3.np.random.choice():
np.random.choice() takes array/list as parameter and randomly returns one value.

## Syntax:
np.random.choice(a,size=None)

In [118]:
np.random.choice(np.arange(1,10),(3,3))

array([[1, 7, 3],
       [3, 8, 3],
       [6, 5, 1]])

In [119]:
np.random.choice(np.arange(1,10))

7

## 4.np.random.uniform(): 
This function generates random numbers from a uniform distribution within a specified range. It returns an array of random numbers with the shape specified by the arguments, and the numbers are evenly distributed within the specified range.

## Syntax:
np.random.uniform(low=0,high=1.0,size)

In [120]:
np.random.uniform(0,50,(3,4))

array([[ 8.87230708,  0.27954566, 34.05357951, 25.55417876],
       [35.49267855, 42.15423167, 42.20585322, 20.0267318 ],
       [36.21753029, 10.39486843, 32.70881629, 29.31215567]])

In [121]:
np.random.uniform()

0.9757388905165043

## 5.np.random.randn(): 
This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). It returns an array of random numbers with the shape specified by the arguments.

## Syntax:
np.random.randn(shape)

In [122]:
np.random.randn()

-1.5470147129232985

In [123]:
np.random.randn(3,4)

array([[ 2.3304884 ,  1.53296196,  0.80674383,  1.95758766],
       [-0.37610738, -1.00333361, -1.29128234,  0.17999903],
       [ 0.65024447,  0.37129812,  0.2190139 , -0.65435638]])

## 6.np.random.shuffle():
shuffles the array in place, meaning it modifies the original array. 

## Syntax:
np.random.shuffle(a1)

In [124]:
x1=np.array([1,2,3,4,5])
x1

array([1, 2, 3, 4, 5])

In [125]:
np.random.shuffle(x1)

In [126]:
x1

array([4, 5, 1, 3, 2])

# Exponential Functions

In NumPy, exponential functions are provided to compute the exponential of each element in an array. Here are the main exponential functions available in NumPy:



## 1.np.exp(x): 
 This function computes the exponential of each element in the input array x. The exponential function calculates 
�
�
e 
x
 , where 
�
e is Euler's number (approximately 2.71828)

## Syntax:
np.exp(a1)

In [127]:
x1

array([4, 5, 1, 3, 2])

In [128]:
np.exp(x1)

array([ 54.59815003, 148.4131591 ,   2.71828183,  20.08553692,
         7.3890561 ])

## 2.np.exp2(x): 
This function computes 
2
�
2 
x
  for each element in the input array x
    
## Syntax:
np.exp2(a1)

In [129]:
x1

array([4, 5, 1, 3, 2])

In [130]:
np.exp2(x1)

array([16., 32.,  2.,  8.,  4.])

## 3.np.expm1(x): 
This function computes 
�
�
−
1
e 
x
 −1 for each element in the input array x. It is useful for computing small values of 
�
�
−
1
e 
x
 −1 accurately.

## Syntax:
np.expm1(a1)

In [131]:
x1

array([4, 5, 1, 3, 2])

In [132]:
np.expm1(x1)

array([ 53.59815003, 147.4131591 ,   1.71828183,  19.08553692,
         6.3890561 ])

# Logarithemic Functions


In NumPy, logarithmic functions are provided to compute the logarithm of each element in an array. Here are the main logarithmic functions available in NumPy:

## 1.np.log(x): 
This function computes the natural logarithm (base e) of each element in the input array x.

## Syntax:
np.log(a1)

In [133]:
x1

array([4, 5, 1, 3, 2])

In [134]:
np.log(x1)

array([1.38629436, 1.60943791, 0.        , 1.09861229, 0.69314718])

## 2.np.log10(x): 
This function computes the base-10 logarithm of each element in the input array x.

## Syntax:
np.log10(a1)

In [135]:
x1

array([4, 5, 1, 3, 2])

In [136]:
np.log10(x1)

array([0.60205999, 0.69897   , 0.        , 0.47712125, 0.30103   ])

## 3.np.log2(x): 
This function computes the base-2 logarithm of each element in the input array x.

## Syntax:
np.log2(a1)

In [137]:
x1

array([4, 5, 1, 3, 2])

In [138]:
np.log2(x1)

array([2.        , 2.32192809, 0.        , 1.5849625 , 1.        ])

# Matrix Functions

NumPy provides various functions for working with matrices, including matrix creation, manipulation, and operations. Here are some commonly used matrix functions in NumPy:

## 1.np.dot():
Matrix multiplication of two arrays.

## Syntax:
np.dot(a,b,out=None)

In [139]:
x1=np.array([[1,2,3],[4,5,6],[7,8,9]])
x2=np.array([[10,11,12],[13,14,15],[16,17,18]])
x1,x2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [140]:
np.dot(x1,x2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

## 2.np.matmul():
Another way to perform matrix multiplication.

## Syntax:
np.matmul(**args,***kwargs)

In [141]:
x1,x2

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [142]:
np.matmul(x1,x2)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

## 3.np.transpose(): 
Computes Transpose of a matrix.

## Syntax:
np.transpose(a)

In [143]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [144]:
np.transpose(x1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [145]:
x1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## 4.np.linalg.inv(): 
Computes Inverse of a matrix.

## Syntax:
np.linalg.inv(a)


In [146]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [147]:
np.linalg.inv(x1)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

## 5.np.linalg.det():
Computes determinant of a matrix.

## Syntax:
np.linalg.det(a)


In [148]:
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [149]:
np.linalg.det(x1)

-9.51619735392994e-16

# Advanced Mathematical Functions in Numpy

## 1.np.nansum(): 
This function computes the sum of array elements over a specified axis, treating NaNs (Not a Number) as zero.

## Syntax:
np.nansum(a,axis=None,dtype=None)

In [150]:
x2=np.array([[1,2,3],[np.nan,6,np.nan],[9,np.nan,8]])
x2

array([[ 1.,  2.,  3.],
       [nan,  6., nan],
       [ 9., nan,  8.]])

In [151]:
np.nansum(x2)

29.0

In [152]:
np.nansum(x2,axis=0)

array([10.,  8., 11.])

In [153]:
np.nansum(x2,axis=1)

array([ 6.,  6., 17.])

## 2.np.cumsum():
This function computes the cumulative sum of array elements along a specified axis. It returns an array containing the cumulative sum of elements up to each position in the input array.

## Syntax:
np.cumsum(a,axis=None,dtype=None)

In [154]:
a1=np.arange(11,20).reshape(3,3)
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [155]:
np.cumsum(a1)

array([ 11,  23,  36,  50,  65,  81,  98, 116, 135], dtype=int32)

In [156]:
np.cumsum(a1,axis=0)

array([[11, 12, 13],
       [25, 27, 29],
       [42, 45, 48]], dtype=int32)

In [157]:
np.cumsum(a1,axis=1)

array([[11, 23, 36],
       [14, 29, 45],
       [17, 35, 54]], dtype=int32)

## 3.np.nanprod(): 
This function computes the product of array elements over a specified axis, treating NaNs (Not a Number) as one.

## Syntax:
np.nanprod(a,axis=None,dtype=None)

In [158]:
x2

array([[ 1.,  2.,  3.],
       [nan,  6., nan],
       [ 9., nan,  8.]])

In [159]:
np.nanprod(x2)

2592.0

In [160]:
np.nanprod(x2,axis=0)

array([ 9., 12., 24.])

In [161]:
np.nanprod(x2,axis=1)

array([ 6.,  6., 72.])

## 4.np.cumprod():
This function computes the cumulative product of array elements along a specified axis. It returns an array containing the cumulative product of elements up to each position in the input array.

## Syntax:
np.cumprod(a,axis=None,dtype=None)

In [162]:
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [163]:
np.cumprod(a1)

array([        11,        132,       1716,      24024,     360360,
          5765760,   98017920, 1764322560, -837609728], dtype=int32)

In [164]:
np.cumprod(a1,axis=0)

array([[  11,   12,   13],
       [ 154,  180,  208],
       [2618, 3240, 3952]], dtype=int32)

In [165]:
np.cumprod(a1,axis=1)

array([[  11,  132, 1716],
       [  14,  210, 3360],
       [  17,  306, 5814]], dtype=int32)

## 5.np.isnan():
Returns True if there ara nan values in the array.

## Syntax:
np.isnan(a1)

In [166]:
x2

array([[ 1.,  2.,  3.],
       [nan,  6., nan],
       [ 9., nan,  8.]])

In [167]:
np.isnan(x2)

array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])

In [168]:
x2[np.isnan(x2)]

array([nan, nan, nan])

## 6.np.isinf():
Returns True if there are inf values in the array.

## Syntax:
np.isinf(a1)

In [169]:
x3=np.array([1,np.inf,3,5,6,8]).reshape(3,2)
x3

array([[ 1., inf],
       [ 3.,  5.],
       [ 6.,  8.]])

In [170]:
np.isinf(x3)

array([[False,  True],
       [False, False],
       [False, False]])

In [171]:
x3[np.isinf(x3)]

array([inf])

## 7.np.where():
np.where() is commonly used in data manipulation tasks, such as filtering, masking, and replacing values in arrays based on specific conditions.

## Syntax:
np.where(condition,[x,y])

In [172]:
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [173]:
np.where(a1>15,"Hello",0)

array([['0', '0', '0'],
       ['0', '0', 'Hello'],
       ['Hello', 'Hello', 'Hello']], dtype='<U11')

## 8.np.apply_along_axis() :
np.apply_along_axis() allows you to apply a function along the specified axis of a NumPy array.

## Syntax:
np.apply_along_axis(funcid,axis,arr)

In [192]:
a1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [198]:
np.apply_along_axis(lambda x:x**2,axis=0,arr=a1)

array([[121, 144, 169],
       [196, 225, 256],
       [289, 324, 361]], dtype=int32)

In [200]:
np.apply_along_axis(max,axis=1,arr=a1)

array([13, 16, 19])

# String Functions


NumPy provides functions for working with arrays of strings through the numpy.char module. Here are some commonly used string functions in NumPy:



## 1.np.char.upper():
Converts all characters in each string to uppercase.

## Syntax:
np.char.upper(a)

In [174]:
s1=np.array(["raghu","Rohan","RoHit","Rahul"])
s1

array(['raghu', 'Rohan', 'RoHit', 'Rahul'], dtype='<U5')

In [175]:
np.char.upper(s1)

array(['RAGHU', 'ROHAN', 'ROHIT', 'RAHUL'], dtype='<U5')

## 2.np.char.lower(): 
Converts all characters in each string to lowercase.

## Syntax:
np.char.lower(a)

In [176]:
s1

array(['raghu', 'Rohan', 'RoHit', 'Rahul'], dtype='<U5')

In [177]:
np.char.lower(s1)

array(['raghu', 'rohan', 'rohit', 'rahul'], dtype='<U5')

## 3.np.char.title():
Converts the first character of each word to uppercase and all other characters to lowercase.

## Syntax:
np.char.title(a)

In [178]:
s1

array(['raghu', 'Rohan', 'RoHit', 'Rahul'], dtype='<U5')

In [179]:
np.char.title(s1)

array(['Raghu', 'Rohan', 'Rohit', 'Rahul'], dtype='<U5')

## 4.np.char.capitalize():
Converts the first character of each string to uppercase and all other characters to lowercase.

## Syntax:
np.char.capitalize(a)

In [180]:
s1

array(['raghu', 'Rohan', 'RoHit', 'Rahul'], dtype='<U5')

In [181]:
np.char.capitalize(s1)

array(['Raghu', 'Rohan', 'Rohit', 'Rahul'], dtype='<U5')

## 5.np.char.split(): 
Splits each string into a list of substrings based on a delimiter

## Syntax:
np.char.split(a,sep=None)

In [182]:
s2=np.array([" Python "," SQL "," ML "," DL "])
s2

array([' Python ', ' SQL ', ' ML ', ' DL '], dtype='<U8')

In [183]:
np.char.split(s2,sep=" ")

array([list(['', 'Python', '']), list(['', 'SQL', '']),
       list(['', 'ML', '']), list(['', 'DL', ''])], dtype=object)

## 6.np.char.strip(): 
Removes leading and trailing whitespace from each string.

## Syntax:
np.char.strip(a)

In [184]:
s2

array([' Python ', ' SQL ', ' ML ', ' DL '], dtype='<U8')

In [185]:
np.char.strip(s2)

array(['Python', 'SQL', 'ML', 'DL'], dtype='<U8')

In [186]:
np.char.lstrip(s2)

array(['Python ', 'SQL ', 'ML ', 'DL '], dtype='<U8')

In [187]:
np.char.rstrip(s2)

array([' Python', ' SQL', ' ML', ' DL'], dtype='<U8')

## 7.np.char.join():
Joins elements of a list of strings with a specified delimiter.

## Syntax:
np.char.join(sep,seq)

In [188]:
s2

array([' Python ', ' SQL ', ' ML ', ' DL '], dtype='<U8')

In [189]:
np.char.join("_",s2)

array([' _P_y_t_h_o_n_ ', ' _S_Q_L_ ', ' _M_L_ ', ' _D_L_ '], dtype='<U15')

# BroadCasting of Arrays
Broadcasting is a powerful mechanism in NumPy that allows arrays of different shapes to be combined together in arithmetic operations. When operating on arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e., rightmost) dimensions and works its way leftward, broadcasting dimensions where necessary to make the shapes compatible for the operation.

The broadcasting rule in NumPy follows these steps:

- If the arrays do not have the same number of dimensions, then the shape of the array with fewer dimensions is padded with ones   on its leading (left) side.
- The sizes of the corresponding dimensions of the two arrays are compared. Two dimensions are compatible if they are equal or     if one of them is 1.
- If the sizes of the corresponding dimensions are different and neither is equal to 1, an error is raised.

In [190]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9]])
arr1+arr2

array([[ 8, 10, 12],
       [11, 13, 15]])

In [191]:
arr1 = np.array([1, 2, 3])
scalar = 5
result1 = arr1 + scalar
result1  

array([6, 7, 8])